---
title: "Data Partition"
author: "Seung Hyun Sung"
date: "2/4/2022"
output: 
    html_document:
        theme: flatly
        toc: true
        toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    message = FALSE,
    warning = FALSE)
```


```{r libraries}
library(tidyverse)
library(fs)
library(timetk)
```


# 1. Data 
```{r}
trans_invoice_tbl <- read_rds("00_Data/data_wranggled/trans_data/trans_invoice_tbl.rds")
```



# 2. Set cohort Span 
- Set initial purchase 
```{r}
first_purhase_tbl <- trans_invoice_tbl %>% 
    group_by(customer_id) %>% 
    slice_min(invoice_date) %>% 
    ungroup()

ids_in_cohort_selected <- first_purhase_tbl %>% 
    # Set Cohort Range
    filter_by_time(
        .start_date = "2009-12",
        .end_date   = "2010-12"
    ) %>% 
    pull(customer_id) 


cohort_selected_tbl <- trans_invoice_tbl %>% 
    filter(customer_id %in% ids_in_cohort_selected)
```


# 3. Train, Validation and Test splitting function
-- Step_1: Random Splitting by Customer id 
-- Step_2: Time Splitting (assessing 90 Days)
-- Step_3: Abstract Validation set from Test data

```{r}
set.seed(43)

ids_train <- cohort_selected_tbl %>% 
    pull(customer_id) %>% 
    unique() %>% 
    sample(size = round(0.8*length(.))) %>% 
    sort()

# Train set 
split_1_train_tbl <- cohort_selected_tbl %>% 
    filter(customer_id %in% ids_train)

ids_validation <- cohort_selected_tbl %>% 
    filter(!customer_id %in% ids_train) %>% 
    pull(customer_id) %>% 
    unique() %>% 
    sample(size = round(0.5*length(.))) %>% 
    sort()
    
split_1_test_tbl <- cohort_selected_tbl %>% 
    filter(!customer_id %in% ids_train) 

```



```{r}
splits_2_train <- time_series_split(
    split_1_train_tbl,
    assess = "90 days",
    cumulative = TRUE
)

splits_2_test <- time_series_split(
    split_1_test_tbl,
    assess = "90 days",
    cumulative = TRUE
)
    
targets_train_tbl <- testing(splits_2_train) %>% 
    group_by(customer_id) %>% 
    summarise(
        spend_90_total = sum(invoice_spend),
        spend_90_flag  = 1 
    )
    
targets_test_tbl <- testing(splits_2_test) %>% 
    group_by(customer_id) %>% 
    summarise(
        spend_90_total = sum(invoice_spend),
        spend_90_flag  = 1
        ) 

training(splits_2_train)

training(splits_2_test)
```

